config/routes.rb
Breadcrumbs::Application.routes.draw do
  devise_for :users, skip: :all
  namespace :admin do
    resources :breads, except: :show do
      collection { post :batch_action }
    end

    resources :helps, only: :index
    resource  :settings, only: [:edit, :update]

    resources :users, except: :show do
      collection { post :batch_action }
    end

    resources :versions, only: [:index, :show] do
      collection { post :batch_action }
    end

    resources :inline_attachments, only: :create
    resources :inline_images, only: [:new, :create, :destroy] do
      post 'add_item', on: :collection
    end

    resources :pages, except: :show do
      collection { post :batch_action }
      member { put :drop }
    end

    root to: 'pages#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'authentications' }
  devise_scope :user do
    get 'authentications/new', to: 'authentications#new'
    post 'authentications/link', to: 'authentications#link'
  end

  root to: 'index#index'

  begin
    Page.for_routes.group_by(&:behavior).each do |behavior, pages|
      pages.each do |page|
        case behavior
        when nil
        else
          resource( "#{page.class.name.underscore}_#{page.id}",
                    path:       page.absolute_path,
                    controller: behavior,
                    only:       :show,
                    page_id:    page.id )
        end
      end
    end
  rescue
    nil
  end
end

app/controllers/admin/helps_controller.rb
class Admin::HelpsController < Admin::BaseController
  def index
  end
end

app/views/admin/helps/index.haml
- title I18n.t('admin.helps.actions.index.title')

= admin_page_header I18n.t('admin.helps.actions.index.header')
%h4
  Общие замечания по&nbsp;добавлению и&nbsp;редактированию информации:
%ul
  %li
    Везде, где можно добавить ту&nbsp;или иную сущность (например, страницу), <b>в правой верхней части страницы есть кнопка «добавить»</b>.
  %li
    Некоторые типы записей могут быть <b>опубликованы</b> (и&nbsp;будут отображаться на&nbsp;сайте) и&nbsp;<b>заархивированы</b> (сохранятся в&nbsp;базе, их&nbsp;можно редактировать, но&nbsp;они не&nbsp;будут опубликованы на&nbsp;сайте). <b>Состояние опубликованной записи обозначается пиктограммой <i class="icon-eye-open"></i> в&nbsp;правой части списка</b> (отсутствие пиктограммы обозначает&nbsp;то, что запись заархивирована).
  %li
    В&nbsp; некоторых списках есть возможность <b>ручной сортировки записей</b> (порядок отображения на&nbsp;сайте и&nbsp;в&nbsp;списках). Иногда требуется вывести какую-то запись раньше предыдущей. Это справедливо, например, для списка страниц. <b>Чтобы переместить запись выше или ниже, достаточно просто перетащить её&nbsp;в&nbsp;нужное место указателем мыши</b> (предварительно нажав левую кнопку мыши, когда указатель находится над пиктограммой <i class="icon-move"></i>).
  %li
    В&nbsp; некоторых списках предусмотрены <b>групповые операции</b>&nbsp;— публикация, архивирование и&nbsp;удаление. Чтобы выполнить групповую операцию, необходимо выбрать записи, с&nbsp;которыми будет осуществляться операция&nbsp;— это можно сделать, отметив эти записи галочками в&nbsp;чекбоксах,&nbsp;— а&nbsp;затем выбрать операцию из&nbsp;списка внизу страницы (нажать на&nbsp;соответствующую кнопку). Эти операции можно выполнять также и&nbsp;с&nbsp;отдельными объектами (то&nbsp;есть по&nbsp;одному), чтобы не&nbsp;заходить на&nbsp;страницу редактирования записи.
  %li
    Если <b>редактирование записей</b> доступно, то&nbsp;в&nbsp;списке присутствует пиктограмма <i class="icon-edit"></i>. Щелчок по&nbsp;этой пиктограмме открывает страницу редактирования соответствующей записи.
  %li
    Все <b>специфичные настройки страниц</b> вынесены в раздел «#{link_to I18n.t('admin.settings.actions.index.header'), edit_admin_settings_path}».
  %li
    В&nbsp;случаях, где это предусмотрено оформлением страниц, текстовые поля оснащены <b>WYSIWYG-редактором</b>. Редактор имеет возможность размещения изображений и&nbsp;вставки кода для видео (embedded video) с&nbsp;сервиса YouTube.
%h4
  Значение пиктограмм:
%ul.legend
  %li
    <i class="icon-edit"></i>
    = I18n.t('admin.helps.actions.index.legend.edit')
  %li
    <i class="icon-remove"></i>
    = I18n.t('admin.helps.actions.index.legend.delete')
  %li
    <i class="icon-move"></i>
    = I18n.t('admin.helps.actions.index.legend.move')
  %li
    <i class="icon-eye-open"></i>
    = I18n.t('admin.helps.actions.index.legend.published')
  %li
    <i class="icon-list"></i>
    = I18n.t('admin.helps.actions.index.legend.nav_published')

-#
  %h4
    Создание и редактирование таблицы
  .p
    Для создания таблицы выберите на панели визуального редактора иконку добавления таблицы. В открывшемся диалоговом окне задайте:
  %ul
    %li необходимое количество столбцов;
    %li необходимое количество строк;
    %li если вы хотите использовать таблицу как сетку, то в поле «класс» выберите класс «blank», тогда оформление таблицы отображаться не будет.
  %p Нажмите кнопку «Вставить».
  %p Заполните таблицу необходимыми данными.
  %p Для выделения заголовков столбцов таблицы:
  %ul
    %li правой кнопкой мыши на строке с заголовками вызовите меню редактирования и выберите пункт «Строка» — «Параметры строки»;
    %li в открывшемся окне задайте «Тип строки» — «Заголовок» и нажмите кнопку «Обновить»;
    %li выделите ячейки строки с заголовками и вызовите меню редактирования;
    %li в меню выберите пункт «Ячейка» — «Параметры ячейки»;
    %li в открывшемся окне задайте «Тип» — «Заголовок» и «Выравнивание». Для заголовков столбцов с числами используйте выравнивание «по правому краю», для всех остальных — «по левому краю», для этого по отдельности выделяейте нужные ячейки;
    %li нажмите кнопку «Обновить».
  %p Для ячеек с числовой информацией аналогичным образом установие выравнивание ячеек «по правому краю».
  %p Для выделения строки с итоговой информацией в конце таблицы:
  %ul
    %li правой кнопкой мыши на строке с заголовками вызовите меню редактирования и выберите пункт «Строка» — «Параметры строки»;
    %li в открывшемся окне задайте «Тип строки» — «Завершение» и нажмите кнопку «Обновить».