config/routes.rb
Breadcrumbs::Application.routes.draw do
  devise_for :users, skip: :all
  namespace :admin do
    resources :breads, except: :show do
      collection { post :batch_action }
    end

    resources :helps, only: :index
    resource  :settings, only: [:edit, :update]

    resources :users, except: :show do
      collection { post :batch_action }
    end

    resources :versions, only: [:index, :show] do
      collection { post :batch_action }
    end

    resources :inline_attachments, only: :create
    resources :inline_images, only: [:new, :create, :destroy] do
      post 'add_item', on: :collection
    end

    resources :pages, except: :show do
      collection { post :batch_action }
      member { put :drop }
    end

    root to: 'pages#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'authentications' }
  devise_scope :user do
    get 'authentications/new', to: 'authentications#new'
    post 'authentications/link', to: 'authentications#link'
  end

  root to: 'index#index'

  begin
    Page.for_routes.group_by(&:behavior).each do |behavior, pages|
      pages.each do |page|
        case behavior
        when nil
        else
          resource( "#{page.class.name.underscore}_#{page.id}",
                    path:       page.absolute_path,
                    controller: behavior,
                    only:       :show,
                    page_id:    page.id )
        end
      end
    end
  rescue
    nil
  end
end

app/models/settings.rb
class Settings < ActiveRecord::Base
  before_validation :sanitize

  validates :company_name, :email, :email_header_from, :per_page, presence: true

  has_paper_trail

  def self.get
    first || new
  end

  private

  def sanitize
    fields = [ :copyright, :email, :index_meta_description, :index_meta_title ]

    fields.each do |attribute|
      self[attribute] = Sanitize.clean self[attribute], elements: ['br']
    end
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::BaseController
  def update
    if resource.update_attributes params[:settings]
      flash[:notice] = t 'flash.actions.update.notice'
      redirect_to action: :edit
    else
      flash[:error] = t 'flash.actions.update.alert'
      render action: :edit
    end
  end

  private

  def resource
    @resource ||= Settings.get
  end
  helper_method :resource
end

app/views/admin/settings/edit.haml
- title 'Настройки'
= resource_header 'Настройки'

= simple_form_for [:admin, resource], url: admin_settings_path, html: { method: :put, class: 'form-horizontal' } do |f|
  .pill-content
    %fieldset
      = f.input :email
      = f.input :email_header_from
      = f.input :per_page, input_html: {class: 'input-mini'}
      = f.input :copyright
    %fieldset
      %legend= I18n.t 'admin.settings.sets.index'
      = f.input :index_meta_title
      = f.input :index_meta_description, as: :string
    %fieldset
      %legend= I18n.t 'admin.settings.sets.contact_information'
      = f.input :company_name
      = f.input :contact_email
    %fieldset
      %legend= I18n.t 'admin.settings.sets.counters'
      = f.input :seo_google_analytics
      = f.input :seo_yandex_metrika
  .form-actions
    = f.button :submit, resource_button_value_main, class: bs_btn(:primary)