config/routes.rb
Breadcrumbs::Application.routes.draw do
  devise_for :users, skip: :all
  namespace :admin do
    resources :breads, except: :show do
      collection { post :batch_action }
    end

    resources :helps, only: :index
    resource  :settings, only: [:edit, :update]

    resources :users, except: :show do
      collection { post :batch_action }
    end

    resources :versions, only: [:index, :show] do
      collection { post :batch_action }
    end

    resources :inline_attachments, only: :create
    resources :inline_images, only: [:new, :create, :destroy] do
      post 'add_item', on: :collection
    end

    resources :pages, except: :show do
      collection { post :batch_action }
      member { put :drop }
    end

    root to: 'pages#index'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'authentications' }
  devise_scope :user do
    get 'authentications/new', to: 'authentications#new'
    post 'authentications/link', to: 'authentications#link'
  end

  root to: 'index#index'

  begin
    Page.for_routes.group_by(&:behavior).each do |behavior, pages|
      pages.each do |page|
        case behavior
        when nil
        else
          resource( "#{page.class.name.underscore}_#{page.id}",
                    path:       page.absolute_path,
                    controller: behavior,
                    only:       :show,
                    page_id:    page.id )
        end
      end
    end
  rescue
    nil
  end
end

app/models/inline_image.rb
class InlineImage < ActiveRecord::Base
  mount_uploader :image, InlineImageUploader

  validates :image, presence: true

  def parse_input preview=nil
    image_url = preview ? image.url(:preview) : image.url
    %Q[<img src="#{image_url}" />]
  end
end

app/controllers/admin/inline_images_controller.rb
class Admin::InlineImagesController < Admin::BaseController
  skip_before_action :verify_authenticity_token, only: [:add_item, :destroy]
  before_action :gallery, only: [:new, :add_item]
  layout :layout

  def create
    @insert = params[:html_insert]
  end

  def add_item
    @image = InlineImage.create({gallery: @gallery}.merge params[:inline_image])
  end

  def resource
    InlineImage.new
  end
  helper_method :resource

  def destroy
    InlineImage.find(params[:id]).destroy
    head :ok
  end

  private

  def layout
    'admin/gallery_images' if action_name == 'new'
  end

  def gallery
    @gallery = true if params[:gallery] == 'true' or params[:gallery] == '1'
    @gallery ||= false
  end
end

app/views/admin/inline_images/_inline_image.haml
.image{ data: { html_insert: @image.parse_input(@gallery) }}
  = image_tag @image.image.preview.url
  = button_to 'Удалить', admin_inline_image_path(@image.id), class: 'delete'

app/views/admin/inline_images/add_item.js.erb
$('#images').append("<%= j render(@image) %>");

app/views/admin/inline_images/create.haml
= render partial: 'shared/admin/inline_insert_string'

app/views/admin/inline_images/new.haml
= form_for resource_form_object, url: admin_inline_images_path do |f|
  = f.file_field :image, multiple: true
  = check_box_tag :gallery, nil, @gallery, style: 'display: none'
  = text_area_tag :html_insert, nil, style: 'display: none'
  .submit= f.submit 'Загрузить'
  #progress
    .bar
  #images